# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStudentName = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStudentName.setObjectName("labelStudentName")
        self.gridLayout.addWidget(self.labelStudentName, 0, 0, 1, 2)
        self.lineEditStudentName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStudentName.setObjectName("lineEditStudentName")
        self.gridLayout.addWidget(self.lineEditStudentName, 0, 2, 1, 1)
        self.labelAttempts = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAttempts.setObjectName("labelAttempts")
        self.gridLayout.addWidget(self.labelAttempts, 1, 0, 1, 2)
        self.spinBoxAttempts = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBoxAttempts.setMinimum(1)
        self.spinBoxAttempts.setMaximum(4)
        self.spinBoxAttempts.setObjectName("spinBoxAttempts")
        self.gridLayout.addWidget(self.spinBoxAttempts, 1, 2, 1, 1)
        self.layoutScores = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutScores.setObjectName("layoutScores")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutScores)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.layoutScores, 2, 1, 1, 2)
        self.labelScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScores.setObjectName("labelScores")
        self.gridLayout.addWidget(self.labelScores, 3, 0, 1, 2)
        self.buttonSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.gridLayout.addWidget(self.buttonSubmit, 5, 0, 2, 3)
        self.labelMessage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")
        self.gridLayout.addWidget(self.labelMessage, 6, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelStudentName.setText(_translate("MainWindow", "Student name:"))
        self.labelAttempts.setText(_translate("MainWindow", "No of attempts:"))
        self.labelScores.setText(_translate("MainWindow", "Scores:"))
        self.buttonSubmit.setText(_translate("MainWindow", "SUBMIT"))
